apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: app-of-apps/staging
    repoURL: https://github.com/cNorspang/demo-argo-apps
    targetRevision: main
