apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-app-development
  name: example-app-development
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: example-app-development
  template:
    metadata:
      labels:
        app: example-app-development
    spec:
      containers:
        - image: gcr.io/google-samples/gb-frontend:v5
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /
              port: http
          name: example-app
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
