apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
  labels:
    use-promoter: "true"
    environment: production
spec:
  project: default
  destination:
    name: "in-cluster"
    namespace: cloud
  sourceHydrator:
    drySource:
      repoURL: https://github.com/cNorspang/demo-argo-apps
      path: apps/example-app
      targetRevision: HEAD
      helm:
        valueFiles:
          - values/prod.yaml
    syncSource:
      targetBranch: environment/prod
      path: apps/example-app
    hydrateTo:
      targetBranch: environment/prod-next
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
